# Generated by Django 3.2.13 on 2022-05-11 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(max_length=50, verbose_name='Образование')),
            ],
            options={
                'verbose_name': 'Образование',
                'verbose_name_plural': 'Образовании',
            },
        ),
        migrations.CreateModel(
            name='ExperinceYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_year', models.CharField(max_length=100, verbose_name='Опыт работы')),
            ],
            options={
                'verbose_name': 'Опыт Работы',
                'verbose_name_plural': 'Опыт Работы',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=50, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Пол',
            },
        ),
        migrations.CreateModel(
            name='HasExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_experience', models.CharField(max_length=50, verbose_name='Имеется ли опыт работы')),
            ],
            options={
                'verbose_name': 'Имеется ли опыт Работы',
                'verbose_name_plural': 'Имеется ли опыт Работы',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Языки')),
            ],
            options={
                'verbose_name': 'Языки',
                'verbose_name_plural': 'Языки',
            },
        ),
        migrations.CreateModel(
            name='Removal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('removal', models.CharField(max_length=50, verbose_name='Готовность к переездам')),
            ],
            options={
                'verbose_name': 'Готовность к переездам',
                'verbose_name_plural': 'Готовность к переездам',
            },
        ),
        migrations.CreateModel(
            name='ScheduleTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.CharField(max_length=100, verbose_name='Режим Работы')),
            ],
            options={
                'verbose_name': 'Режим Работы',
                'verbose_name_plural': 'Режим Работы',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=100, verbose_name='Навыки')),
            ],
            options={
                'verbose_name': 'Навыки',
                'verbose_name_plural': 'Навыки',
            },
        ),
        migrations.CreateModel(
            name='TimeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_work', models.CharField(max_length=100, verbose_name='График Работы')),
            ],
            options={
                'verbose_name': 'График Работы',
                'verbose_name_plural': 'График Работы',
            },
        ),
        migrations.CreateModel(
            name='CreateResume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('birth_date', models.DateField(verbose_name='Дата Рождения')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Фото')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок Резюме')),
                ('salary', models.CharField(max_length=100, verbose_name='Желаемая Зароботная Плата')),
                ('last_place_work', models.CharField(blank=True, max_length=100, null=True, verbose_name='Последние место работы')),
                ('data_finish', models.DateField(blank=True, null=True, verbose_name='Конец')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Название Компании')),
                ('status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность предыдущий работы')),
                ('info', models.CharField(blank=True, max_length=100, null=True, verbose_name='Рабочие обязанности')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_choices', to='worker1.category', verbose_name='Категория')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='city_choices', to='worker1.city', verbose_name='Город')),
                ('education', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='education_choices', to='worker1.education', verbose_name='Образование')),
                ('experience_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experince_year', to='worker1.experinceyear', verbose_name='Опыт работы годами')),
                ('gender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gender_choices', to='worker1.gender', verbose_name='Пол')),
                ('has_experience', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='has_experience_choices', to='worker1.hasexperience', verbose_name='Опыт работы')),
                ('language', models.ManyToManyField(related_name='languages_choices', to='worker1.Language', verbose_name='Языки')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_ids', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_time_choices', to='worker1.scheduletime', verbose_name='Режим Работы')),
                ('skills', models.ManyToManyField(related_name='skills_choices', to='worker1.Skills', verbose_name='Навыки')),
                ('time_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_work_choices', to='worker1.timework', verbose_name='График Работы')),
                ('travel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='removal_choices', to='worker1.removal', verbose_name='Готовность к переездам')),
            ],
            options={
                'verbose_name': 'Резюме',
                'verbose_name_plural': 'Резюме',
            },
        ),
    ]
